Feat/create invest crypto
notuslabs/chainless-app pull request #19
Opened 2024-01-05 19:06 UTC by Tiago138

## Why

We need a way for the final user to buy brz and usdc with pix, and there was a need for the user to be able to buy cryptocurrency.

## Changes

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

- Add functionality to buy brz and usdc with pix.
- Add functionality to sell brz and usdc with pix.
- Created screens for buy and sell cryptocurrency.
- Integrated with coingecko api to get tokens data.
- Created line chart.

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2024-01-05 19:21 UTC, Bmullerc approved these changes
LGTM

2024-01-05 21:18 UTC, nicholascostadev approved these changes

2024-01-05 21:18 UTC, nicholascostadev commented on src/components/receipts/WithdrawPixReceipt.tsx
> +const currentDate = new Date();
Shouldn't this be inside the component to be recomputed if needed?

2024-01-05 21:18 UTC, nicholascostadev commented on src/components/receipts/WithdrawPixReceipt.tsx
> +          Chave pix
Shouldn't "pix" be capitalized as "PIX"?

2024-01-05 21:18 UTC, nicholascostadev commented on src/components/receipts/WithdrawRwaReceipt.tsx
> +const currentDate = new Date();
Shouldn't this be inside the component to be recomputed if needed?

2024-01-05 21:18 UTC, nicholascostadev commented on src/components/receipts/WithdrawalReceipt.tsx
> +const currentDate = new Date();
Shouldn't this be inside the component to be recomputed if needed?

2024-01-05 21:18 UTC, nicholascostadev commented on src/screens/AmountInput.tsx
> +                R$ {selectedCurrency.balance}
Don't you have a function to format this?

2024-01-05 21:18 UTC, nicholascostadev commented on src/screens/Asset/ConfirmInvestRWA.tsx
> +            <Label size="md-bold">Enviado transação...</Label>
Missing an "n"

```suggestion
            <Label size="md-bold">Enviando transação...</Label>
```

2024-01-05 21:18 UTC, nicholascostadev commented on src/screens/ConfirmDepositPix.tsx
> +              Chave pix Transfero
Shouldn't "pix" be capitalized as "PIX"?

```suggestion
              Chave PIX Transfero
```

2024-01-05 21:18 UTC, nicholascostadev commented on src/screens/balanceWithdrawal/ConfirmWithdrawPix.tsx
> +const date = new Date();
Shouldn't this date be inside the component so that it recomputes if needed?

2024-01-05 21:18 UTC, nicholascostadev commented on src/screens/balanceWithdrawal/ConfirmWithdrawPix.tsx
> +            <Label size="md-bold">Sending Transaction...</Label>
It should be in portuguese

```suggestion
            <Label size="md-bold">Enviando Transação...</Label>
```

2024-01-05 21:18 UTC, nicholascostadev commented on src/screens/balanceWithdrawal/ConfirmWithdrawPix.tsx
> +                id="jdksjfkljslkfdj"
Is it fine to leave this Id that way?

2024-01-05 21:18 UTC, nicholascostadev commented on src/screens/balanceWithdrawal/ConfirmWithdrawPix.tsx
> +            {/* )} */}
Remove empty comment

```suggestion
```

2024-01-05 21:18 UTC, nicholascostadev commented on src/screens/cryptocurrency/CryptocurrencyInfo.tsx
> +type CryptocurrencyInfoProps = {
It should be capitalized

```suggestion
type CryptoCurrencyInfoProps = {
```

2024-01-05 21:18 UTC, nicholascostadev commented on src/screens/cryptocurrency/CryptocurrencyInfo.tsx
> +export default function CryptocurrencyInfo({
It should be capitalized

```suggestion
export default function CryptoCurrencyInfo({
```

2024-01-05 21:18 UTC, nicholascostadev commented on src/screens/cryptocurrency/CryptocurrencyInfo.tsx
> +  cryptocurrency: string;
It should be capitalized

```suggestion
  cryptoCurrency: string;
```

2024-01-05 21:18 UTC, nicholascostadev commented on src/screens/cryptocurrency/SelectCryptocurrency.tsx
> +type SelectCryptocurrencyProps = {
It should be capitalized

```suggestion
type SelectCryptoCurrencyProps = {
```

2024-01-05 21:18 UTC, nicholascostadev commented on src/screens/cryptocurrency/SelectCryptocurrency.tsx
> +  OnSelectCryptocurrency: (event: Event) => void;
It should be capitalized

```suggestion
  OnSelectCryptoCurrency: (event: Event) => void;
```

2024-01-05 21:18 UTC, nicholascostadev commented on src/screens/cryptocurrency/SelectCryptocurrency.tsx
> +export default function SelectCryptocurrency({
It should be capitalized

```suggestion
export default function SelectCryptoCurrency({
```

2024-01-05 21:21 UTC, nicholascostadev requested changes
Forgot to add "Request Changes"

2024-01-08 12:45 UTC, Tiago138 commented on src/app/(app)/(modals)/fixedincome/index.tsx
> +        {id ? <ConfirmInvestRWA key="5" asset={id} /> : <></>}
You need to return an element here.

2024-01-08 12:45 UTC, Tiago138 commented on src/app/(app)/(modals)/fixedincome/index.tsx
> +        )}
You need to return an element here.

2024-01-08 12:52 UTC, Tiago138 commented on src/components/receipts/InvestmentReceipt.tsx
> +const currentDate = new Date();
I just want to know the time when the component is mounted, if it changes the time when the component renderers it is not useful, in the future the time should come from the backed.

2024-01-08 13:08 UTC, nicholascostadev commented on src/app/(app)/(modals)/cryptocurrency/index.tsx
> +export default function Cryptocurrency() {
Got it, my bad

2024-01-08 13:11 UTC, Tiago138 commented on src/components/card/MulticurrencyCard.tsx
>  export default function MulticurrencyCard({
Multicurrency is a single word.
https://www.merriam-webster.com/dictionary/multicurrency

2024-01-08 13:15 UTC, Tiago138 commented on src/screens/balanceWithdrawal/ConfirmWithdrawPix.tsx
> +            {/* )} */}
This is commented because will be used in the future.

2024-01-08 13:18 UTC, Tiago138 commented on src/screens/balanceWithdrawal/ConfirmWithdrawPix.tsx
> +                id="jdksjfkljslkfdj"
This is here because it is in the design but the back end does not return an id, it needs confirmation if it will be there in the future.

2024-01-10 13:02 UTC, merged